# Generated by Django 2.2 on 2022-02-25 05:58

from django.db import migrations, models
import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_user_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('travel_name', models.CharField(max_length=20)),
                ('travel_link', models.URLField(validators=[posts.validators.validate_travel_lisk])),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('image1', models.ImageField(upload_to='travel_pics')),
                ('image2', models.ImageField(blank=True, upload_to='travel_pics')),
                ('image3', models.ImageField(blank=True, upload_to='travel_pics')),
                ('content', models.TextField()),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
                ('dt_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(error_messages={'unique': '이미 사용중인 닉네임 입니다.'}, max_length=15, null=True, unique=True, validators=[posts.validators.validate_no_special_characters]),
        ),
    ]
